### PR TITLE
improved docs

### PR DESCRIPTION
**Pull request by Piyush27co**

### CODE REVIEW

**Review by budgetpreneur — COMMENTED** [review]
This is public repo. Any changes will be done to private repo. Those private repo changes will be pushed to public.
This PR change can be moved to private repo and can be considered for next/upcoming push/release.

**Review by budgetpreneur — COMMENTED** [review]
"#Write some headline for user" is invalid PR.
Perhaps you intend "### PubNub Java-based SDKs for Java / Android" to make it bigger with single # like "# PubNub Java-based SDKs for Java / Android"

**Comment by Piyush27co** [comment]
Merger it

**Comment by budgetpreneur** [comment]
Thank you for your contribution. We will review it and update in our private repo. The same will be updated here.

**Pull request closed without merging**
