### PR TITLE
Update .pubnub.yml

### PR DESCRIPTION
**Pull request by techwritermat**

### CODE REVIEW

**Comment by parfeon** [comment]
@techwritermat is there something wrong? It was like that for pretty long time

**Comment by techwritermat** [comment]
Yeah, the `v` is messing up our automatic link generation.

**Comment by parfeon** [comment]
@techwritermat it will still appear with each release. You need to change [this](https://github.com/pubnub/java/blob/master/.github/workflows/release/versions.json#L3) object and include:
```json
"clearedPrefix": true,
"clearedSuffix": false
```

This way you instruct deployment pipeline to exclude any prefix from version added into `.pubnub.yml` version.

**Comment by parfeon** [comment]
@techwritermat I've updated `versions.json` file with new pattern, which will exclude `v` prefix.

**Review by kleewho — APPROVED** [review]
LGTM

**Pull request merged**
