### PR TITLE
Remove unused commons-lang dependency

### PR DESCRIPTION
**Pull request by dhleong**
This unused dependency pulls in ~3K methods. When Android's dex limit is 65K, that is a lot.

### CODE REVIEW

**Comment by theoegui** [comment]
Cool!

**Comment by MaxPresman** [comment]
@dhleong thank you for the PR; we'll double check and perform a cut after the weekend! :+1:

**Comment by dhleong** [comment]
Great! :)

**Comment by devendram** [comment]
@dhleong @MaxPresman this is not unused, its required as of now .

**Comment by dhleong** [comment]
Can you point out how and where it's used? It seems to work without it (though I obviously haven't used it in production)

**Comment by devendram** [comment]
@dhleong https://github.com/pubnub/java/blob/master/java/src1/com/pubnub/api/PubnubUtil.java#L13

**Comment by dhleong** [comment]
Okay, interesting that it compiled fine without it. I'll just replicate that single function inline there.

**Comment by dhleong** [comment]
Please see the new PR with a reimplementation in #52

**Pull request closed without merging**
